apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asteroids
  name: asteroids
spec:
  replicas: 2
  selector:
    matchLabels:
      app: asteroids
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: asteroids
    spec:
      containers:
      - image: fullaware/asteroids-app
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        name: asteroids
        envFrom:
        - configMapRef:
            name: asteroids-config
