apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asteroids
resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - asteroids-dbcreation-script-configmap.yaml
  - asteroids-configmap.yaml
  - ingress.yaml
  - mariadb-secret.yaml
  - mariadb-service.yaml
  - mariadb-sts.yaml 
patches:
  - target:
      kind: Ingress
      name: asteroids-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: the.real.hostname