version: "3.9"
services:
    api:
        env_file:
            - api/.env
        build: 
            dockerfile: api/Dockerfile
            context: ./
        container_name: asteroids-api
        image: fullaware/asteroids-api
        ports: 
            - "8088:8088"
        networks:
            - default
    app:
        env_file:
            - app/.env
        build: 
            dockerfile: app/Dockerfile
            context: ./
        container_name: asteroids-app
        image: fullaware/asteroids-app
        ports: 
            - "8080:8080"
        links: 
            - api
        networks:
            - default
