version: "3.9"
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
           MYSQL_ROOT_PASSWORD: I@mR00t
           MYSQL_DATABASE: asteroids
        ports:
            - "3306:3306"
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
    api:
        env_file:
            - api/.env
        build: 
            dockerfile: api/Dockerfile
            context: ./
        container_name: asteroids-api
        image: fullaware/asteroids-api
        ports: 
            - "8088:8088"
        networks:
            - default
    app:
        env_file:
            - app/.env
        build: 
            dockerfile: app/Dockerfile
            context: ./
        container_name: asteroids-app
        image: fullaware/asteroids-app
        ports: 
            - "8080:8080"
        links: 
            - api
        networks:
            - default
